### ISSUE TITLE
Duplicate Mystical Agriculture Seed with staff of the farmer

### ISSUE THREAD

**Issue by MokuJinJin** [kwpugh/gobber#55] opened 2020-06-04 23:04 UTC
Mystical Agriculture v3.0.5
Gobber 2 v2.2.97
Minecraft v1.15.2

MokuJin modpack v1.1.0  [curse](https://www.curseforge.com/minecraft/modpacks/mokujin-pack/)

When i use staff of the farmer near M.A plant, it gave me the regular drop (intended) and the corresponding seed (not intended)

This way i produce seed in a wrong way.

This is not really a duplicate but english is not my first langage, and i don't know how to say it.

**Comment by kwpugh** [comment] 2020-06-05 00:02
What is being duplicated?   I just tested and breaking the mystical crops drop essence and seed.

**Comment by MokuJinJin** [comment] 2020-06-05 06:52
What i mean by duplicate, it's not intended to drop seed.

It should drop only the essence.

crafting a seed is high cost, if with one seed i have unlimmited seed, the only word came to mind is duplicate. I'm sorry for my poor choose of word.

the staff of the farmer don't break mystical crop, the seed stay in the farmland, and it drop essence and seed.

**Comment by kwpugh** [comment] 2020-06-05 11:33
I understand now.   Ir drops the seed and leaves the crop planted (which creates the opportunity to get more seeds).

**Comment by MokuJinJin** [comment] 2020-06-05 14:46
Exactly. I'm glad we understand each other. Do you think it's a bug ?

**Comment by kwpugh** [comment] 2020-06-05 14:50
Well.  It is not exactly a bug, since the staff is working as intended.  It is more of a question of game play balance, since the MA seed are so expensive to make.

**Comment by MokuJinJin** [comment] 2020-06-06 00:35
How can i ajust this ?

**Comment by kwpugh** [comment] 2020-06-06 00:56
Since I cannot control what crops drop, the best I could do is provide a config option to disable the automatic re-planting after crop is harvested.   This would require the replanting of the harvested seed manually.

**Comment by kwpugh** [comment] 2020-06-06 01:21
I uploaded v99 of Gobber on Curseforge, it has options to disable the auto replanting.

**Comment by kwpugh** [comment] 2020-06-06 03:36
I'm closing this out, since there is nothing I can do about this.

**Closed by kwpugh** 2020-06-06 03:36 UTC
Labels: enhancement, question
