### ISSUE TITLE
[1.18.1] Gooey Beef Crash

### ISSUE THREAD

**Issue by willtarax** [kwpugh/gobber#120] opened 2022-01-07 21:38 UTC
Playing Gobber2-Forge-1.18.1-2.6.11

Player picked up gooey beef, and his game crashes whenever he hovers over it with his curser. Please see this pastebin for the crash log

https://pastebin.com/gPZKiiph

**Comment by kwpugh** [comment] 2022-01-07 22:13
Looks like this may be caused by Primal Magick writing data to item and crashes when player hovers over it.

Possibly related: https://github.com/daedalus4096/PrimalMagick/issues/58
and https://github.com/daedalus4096/PrimalMagick/issues/60

**Comment by kwpugh** [comment] 2022-01-15 12:58
This issue appears to be fixed as of version 2.0.2 of Primal Magick.

**Closed by kwpugh** 2022-01-15 12:58 UTC
Labels: bug
